# Generated by Django 3.2.16 on 2022-11-21 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
