version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.10.8"
    resource_class: small
    steps:
      - checkout
      - run:
          name: Initialize venv & req
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Flake8 Linting
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Testing
          command: |
            . venv/bin/activate
            pytest
  # test:
  #   working_directory: ~/circleci-python
  #   docker:
  #     - image: "circleci/python:3.10.8"
  #   steps:
  #     - checkout
    # - run: python3 #main-test.py

workflows:
  main:
    jobs:
      - build
          # requires:
            # - build