version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.10.8"
        auth:
          username: arthur.poullain@gmail.com
          password: $DOCKERHUB_PASSWORD
    resource_class: small
    steps:
      - checkout
      - run:
          name: Initialize venv & req
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Flake8 Linting
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Testing
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: Build and Push Docker Image To Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  main:
    jobs:
      - build
