version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.10.8"
    resource_class: small
    steps:
      - checkout
      - run:
          name: Initialize venv & req
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install wheel
            pip install -r requirements.txt
      - persist_to_workspace:
          root: ~/circleci-python
          paths:
            - venv
      - run:
          name: Flake8 Linting
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Testing
          command: |
            . venv/bin/activate
            pytest
            which python

  containerize:
    docker:
      - image: "cimg/python:3.10.8"
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/circleci-python
      - run:
          name: Send Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_LOGIN --password-stdin
            docker build -t oc_lettings_site .
            docker tag oc_lettings_site $DOCKERHUB_LOGIN/$DOCKER_REPOSITORY:$CIRCLE_SHA1
            docker push $DOCKERHUB_LOGIN/$DOCKER_REPOSITORY:$CIRCLE_SHA1
workflows:
  main:
    jobs:
      - build
      - containerize:
          requires:
            - build
          # filters:
            # branches:
              # only:
                # - main
      - deploy:
          requires:
            - build
            - containerize
          filters:
            branches:
              only:
                - main
